Filtros
InTechMOM/team-9-back pull request #10
Opened 2023-05-26 17:14 UTC by LeidyTatianaMartinezA

[Se agrego los filtros en la API de todos los usuarios. Se actualizo en swagger el link del deploy ya que estaba tomando el localhost.](https://github.com/InTechMOM/team-9-back/pull/7)

2023-05-28 05:02 UTC, KarenEchavarria requested changes

2023-05-28 05:02 UTC, KarenEchavarria commented on src/controllers/users/userControllers.js
> -  if (!userGetById) {
Esta validación no la puedes manejar en el catch como la tienes en la línea 42 porque el catch solo se ejecuta cuando hay errores. En el escenario que una api no encuentre un registro en la base de datos, te va a retornar null, pero esto en si mismo no es un error, por eso hay que poner una validación extra que retorne el 404 manualmente.
Deberías dejar esta validación dentro del catch, igual con los otros controladores

2023-05-30 03:11 UTC, LeidyTatianaMartinezA commented on src/controllers/users/userControllers.js
> -  if (!userGetById) {
Corregido :D

2023-05-30 06:28 UTC, KarenEchavarria requested changes

2023-05-30 06:28 UTC, KarenEchavarria commented on src/routes/userRoutes.js
> + *   name: users
En la línea 127 tienes otra declaración de tag de usuarios, te sugiero que la borres, porque te quedó doble
![image](https://github.com/InTechMOM/team-9-back/assets/39247079/ac0c64da-b3df-4e92-b34b-4a9f20da5e81)

2023-05-30 13:35 UTC, LeidyTatianaMartinezA commented on src/routes/userRoutes.js
> + *   name: users
Solucionado.

2023-05-31 17:51 UTC, merged