Filtros
InTechMOM/team-9-back pull request #7
Opened 2023-05-24 23:55 UTC by LeidyTatianaMartinezA

Se agrego los filtros en la API de todos los usuarios.
Se actualizo en swagger el link del deploy ya que estaba tomando el localhost.

2023-05-25 11:57 UTC, KarenEchavarria requested changes

2023-05-25 11:57 UTC, KarenEchavarria commented on src/controllers/users/userControllers.js
> +  const { email, rol } = request.query;
Hola, te dejo un comentario del controlador createUsers.

El if no tiene mucho sentido de la forma en que está planteado, porque no está atajando y evitando que rompa el servidor en realidad. Lo único que puede recibirnos un error y manejarlo es el catch de la promesa, así que podemos agregar try - catch para manejar ese error. 

También es muy importante retornar en las funciones.

Te quedaría de la siguiente forma:

```
export const createUsers = async (request, response) => {
	try {
		const { name, lastName, email, rol } = request.body;
		const newUser = new Users({ name, lastName, email, rol });
		const userSaved = await newUser.save();
		return response.status(200).json(userSaved);
	} catch (error) {
		return response.status(500).json({ message: "Internal Server Error" });
	}
}
```

2023-05-25 11:57 UTC, KarenEchavarria commented on src/controllers/users/userControllers.js
> +  const { email, rol } = request.query;
puedes aprovechar y agregar try/catch a tus otros controladores

2023-05-26 17:13 UTC, LeidyTatianaMartinezA commented
Se agrego try-catch y manejo de errores en el controlador. 
Se actualizo documentación con cambios

2023-05-26 17:13 UTC, closed without merging